name: Sync with Hugging Face Hub
on:
  push:
    branches:
      - ui  # Trigger the action on pushes to the main branch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Sync with Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: 'harshalmore31/swarms'
          huggingface_repo_id: 'harshalmore31/Swarms'
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: 'space'
          space_sdk: 'gradio'
