name: Sync with Hugging Face Hub
on:
  push:
    branches:
      - master  # Trigger the action on pushes to the master branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Sync with Hugging Face
        run: |
          from huggingface_hub import HfApi
          import os
          import shutil

          # Initialize the Hugging Face API
          api = HfApi()

          # Define the local path to the 'ui' directory
          local_ui_path = 'swarms/structs/ui'

          # Define the remote repository ID (replace with your actual repository ID)
          repo_id = 'harshalmore31/Swarms'

          # Define the path in the repository where you want to upload the files
          repo_path = 'ui'

          # Upload the contents of the 'ui' directory to the Hugging Face Space
          api.upload_folder(
              folder_path=local_ui_path,
              repo_id=repo_id,
              repo_type='space',
              path_in_repo=repo_path
          )
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
